resources:
  - name: supermarket-master
    type: git
    source:
      uri: https://github.com/littlebrownham/supermarket
      branch: master

  # - name: supermarket-docker-image
  #   type: docker-image
  #   source:
  #     repository: dnguy078/market
  #     username: {{dockerhub-username}}
  #     password: {{dockerhub-password}}

jobs:
  - name: unit-test
    plan:
    - get: supermarket-master
    - task: unit
      file: supermarket-master/jobs/market.yaml
      on_success: 
        task: build-go-binary
        file: supermarket-master/jobs/build.yaml
 


  # - name: build-docker-image
  #   plan:
  #   - get: supermarket-master
  #   - put: supermarket-docker-image
  #     params: {build: .}
