resources:
  - name: supermarket-master
    type: git
    source:
      uri: https://github.com/littlebrownham/supermarket
      branch: master

jobs:
  - name: unit-test
    plan:
    - get: supermarket-master
    - task: unit
      file: supermarket-master/jobs/market.yaml