resources:
  - name: supermarket-master
    type: git
    source:
      uri: https://github.com/littlebrownham/supermarket
      branch: master

  - name: supermarket-docker-image
    type: docker-image
    source:
      repository: dnguy078/market
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

jobs:
  - name: unit-test
    plan:
    - get: supermarket-master
    - task: unit
      file: supermarket-master/jobs/market.yaml
 
  - name: publish
    plan:
    - passed: [unit-test]
    - get: supermarket-master
    - task: task-build
      file: supermarket-master/jobs/build.yaml
    - put: supermarket-docker-image
      params: {build: supermarket-master}
